name: Generate Docs
description: >
  Generates SDK documentation using Dokka, and pushes the generated documentation
  to the current branch.
runs:
  using: composite
  steps:
    - run: ./gradlew clean dokkaGfm
      shell: bash
    - run: mkdir docs || true
      shell: bash
    - run: rm -rf docs/generated/ || true
      shell: bash
    - run: mv sdk/build/dokka/gfm/ docs/generated/
      shell: bash
    - run: git add docs/generated
      shell: bash
    - run: |
        if [[ `git status --porcelain` ]]; then
          git config user.email opensource@swedbankpay.com
          git config user.name "Swedbank Pay"
          git commit -m "Update generated documentation"
          git push
        else
          echo No changes to generated documentation
        fi
      shell: bash