name: Run Checks

on: push

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Run Checks with Gradle
        run: ./gradlew check
