name: Upload to Bintray
# This workflow builds and uploads each release to Bintray
on:
  release:
    types: [created]
jobs:
  build:
    name: Upload
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ./gradlew bintrayUpload
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          # TODO: these are not really secret
          BINTRAY_REPO: ${{ secrets.BINTRAY_REPO }}
          BINTRAY_PKG: ${{ secrets.BINTRAY_PKG }}